# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: v2
name: oci-onm-logan
description: Charts for sending Kubernetes platform logs, compute logs, and Kubernetes Objects information to OCI Logging Analytics.
type: application
version: 3.1.1
appVersion: "3.0.0"

dependencies:
- name: oci-onm-common
  version: "3.0.2"
  repository: "file://../common"
  condition: oci-onm-common.enabled
