{{- if eq (include "common.createServiceAccount" .) "true" }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "common.resourceNamePrefix" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "common.resourceNamePrefix" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "common.resourceNamePrefix" . }}
  namespace: {{ include "common.namespace" . }}
{{- end }}
