# Copyright (c) 2023, 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

{{- if eq (include "common.createServiceAccount" .) "true" }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "common.resourceNamePrefix" . }}
  namespace: {{ include "common.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "common.resourceNamePrefix" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "common.resourceNamePrefix" . }}
  namespace: {{ include "common.namespace" . }}
{{- end }}
