global:
  # Kubernetes Namespace in which the resources to be created. Set oci-kubernetes-monitoring-common:createNamespace set to true, if the namespace doesn't exist.
  namespace: test-namespace
  # Prefix to be attached to resources created through this chart. Not all resources may have this prefix.
  resourceNamePrefix: oci-kubernetes-monitoring
  # OKE OCID for an OKE cluster or an unique ID for other Kubernetes clusters.
  kubernetesClusterID: "testID"
  # Provide a unique name for the cluster. This would help uniquely identifying the logs and metrics data at OCI Logging Analytics and OCI Monitoring respectivelt, when moitoring multiple clustersa
  kubernetesClusterName: "testName"
oci-kubernetes-monitoring-common:
  # By default, a cluster role, cluster role binding and serviceaccount will be created for the monitoring pods to be able to (readonly) access various objects within the cluster, to support collection of various telemetry data. You may set this to false and provide your own serviceaccount which has the necessary cluster role(s) binded to it. Refer, README for the cluster role definition and other details.
  createServiceAccount: true
  # If createNamespace is set to true, it tries to create the namespace defined in 'namespace' variable.
  createNamespace: true
  # Kubernetes Namespace in which the serviceaccount to be created.
  namespace: "{{ .Values.global.namespace }}"
  # Prefix to be attached to resources created through this chart. Not all resources may have this prefix.
  resourceNamePrefix: "{{ .Values.global.resourceNamePrefix }}"
  # Name of the Kubernetes ServiceAccount
  serviceAccount: "{{ .Values.global.resourceNamePrefix }}-serviceaccount"
oci-la-fluentd:
  common:
    enabled: false
  namespace: "{{ .Values.global.namespace }}"
  serviceAccount: "{{ .Values.global.resourceNamePrefix }}-serviceaccount"
  kubernetesClusterID: "{{ .Values.global.kubernetesClusterID }}"
  kubernetesClusterName: "{{ .Values.global.kubernetesClusterName }}"
  image:
    url: container-registry.oracle.com/oci_observability_management/oci-la-fluentd-collector:1.0.0
  # Go to OCI Logging Analytics Administration, click Service Details, and note the namespace value.
  ociLANamespace: test
  # OCI Logging Analytics Default Log Group OCID
  ociLALogGroupID: test
mgmtagent_helm:
  common:
    enabled: false
  namespace: "{{ .Values.global.namespace }}"
  serviceAccount: "{{ .Values.global.resourceNamePrefix }}-serviceaccount"
  kubernetesCluster:
    name: "{{ .Values.global.kubernetesClusterName }}"
  mgmtagent:
    # Provide either installKeyFileContent or installKey as an install key. If both provided then installKeyFileContent will take higher precedence.
    # Provide the base64 encoded content of the Management Agent Install Key file
    installKeyFileContent:
    # Copy the downloaded Management Agent Install Key file under root helm directory as resources/input.rsp
    installKey: resources/input.rsp
    # Follow steps documented at https://github.com/oracle/docker-images/tree/main/OracleManagementAgent to build docker image.
    image:
      # Replace this value with actual docker image URL for Management Agent
      url:
      # Image secrets to use for pulling container image (base64 encoded content of ~/.docker/config.json file)
      secret:
