# Copyright (c) 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

{{- if .Values.deployment.daemonSetDeployment }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
  namespace: {{ include "mgmt-agent.namespace" . }}
  labels:
    app: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
spec:
  selector:
    matchLabels:
      app: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
  template:
    metadata:
      annotations:
        checksum/metrics-configmap: {{ include (print $.Template.BasePath "/metrics-configmap.yaml") . | sha256sum }}
        checksum/agent-configmap: {{ include (print $.Template.BasePath "/agent-configmap.yaml") . | sha256sum }}
        checksum/env-configmap: {{ include (print $.Template.BasePath "/env-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
    spec:
      securityContext:
        runAsUser: {{ default 0 .Values.deployment.security.runAsUser }}
        runAsGroup: {{ default 0 .Values.deployment.security.runAsGroup }}
        fsGroup: {{ default 0 .Values.deployment.security.fsGroup }}
      serviceAccountName: {{ include "mgmt-agent.serviceAccount" . }}
      {{- if or .Values.tolerations .Values.global.tolerations }}
      tolerations:
      {{- include "mgmt-agent.mergeTolerations" . | nindent 8 }}
      {{- end }}
      {{- if .Values.mgmtagent.image.secret }}
      imagePullSecrets:
        - name: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent-container-registry-key
      {{- end }}
      restartPolicy: Always
      containers:
        - name: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
          image: {{ .Values.mgmtagent.image.url }}
          envFrom:
          - configMapRef:
              name: {{ include "mgmt-agent.resourceNamePrefix" . }}-env
          env:
            {{- if .Values.mgmtagent.extraEnv }}
            {{- range .Values.mgmtagent.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
            {{- end }}
          resources:
            requests:
              cpu: {{ .Values.deployment.resource.request.cpuCore }}
              memory: {{ .Values.deployment.resource.request.memory }}
            limits:
              cpu: {{ .Values.deployment.resource.limit.cpuCore }}
              memory: {{ .Values.deployment.resource.limit.memory }}
          volumeMounts:
            - name: mgmtagent-secret
              mountPath: /opt/oracle/mgmtagent_secret
              readOnly: true
            - name: mgmtagent-hostpath
              mountPath: /opt/oracle
            - name: mgmtagent-config
              mountPath: /opt/oracle/mgmtagent_config
            - name: mgmtagent-env
              mountPath: /opt/oracle/mgmtagent_env
            - name: mgmtagent-agent-config
              mountPath: /opt/oracle/mgmtagent_agent_config
            - mountPath: /tmp
              name: tmp
          securityContext:
           allowPrivilegeEscalation: false
           readOnlyRootFilesystem: true
      {{- if .Values.deployment.daemonSet.overrideOwnership }}
      initContainers:
        - name: change-ownership-container
          image: container-registry.oracle.com/os/oraclelinux:8-slim
          command: ["/bin/sh", "-c", "chmod 750 /opt/oracle && chown -R {{ .Values.deployment.security.runAsUser }}:{{ .Values.deployment.security.runAsGroup }} /opt/oracle"]
          securityContext:
            runAsUser: 0
            privileged: true
          volumeMounts:
          - name: mgmtagent-hostpath
            mountPath: /opt/oracle
      {{- end }}
      volumes:
        - name: mgmtagent-secret
          secret:
            secretName: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent-rsp
        - name: mgmtagent-config
          configMap:
            name: {{ include "mgmt-agent.resourceNamePrefix" . }}-metrics
        - name: mgmtagent-env
          configMap:
            name: {{ include "mgmt-agent.resourceNamePrefix" . }}-env
        - name: mgmtagent-agent-config
          configMap:
            name: {{ include "mgmt-agent.resourceNamePrefix" . }}-agent
        - name: mgmtagent-hostpath
          hostPath: 
            path: "{{ required "deployment.daemonSet.hostPath is required" .Values.deployment.daemonSet.hostPath }}"
            {{- if regexMatch "^/opt/oracle/*$" .Values.deployment.daemonSet.hostPath }}
            {{- fail "Error: deployment.daemonSet.hostPath cannot be /opt/oracle. Please provide another location or create a sub-directory under /opt/oracle and use that as hostPath" }}
            {{- end }}
        - emptyDir: {}
          name: tmp
{{- end }}
