# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

{{- if not .Values.deployment.daemonSetDeployment }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
  namespace: {{ include "mgmt-agent.namespace" . }}
  labels:
    app: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
spec:
  serviceName: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/metrics-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
    spec:
      securityContext:
        runAsUser: {{ default 0 .Values.deployment.security.runAsUser }}
        runAsGroup: {{ default 0 .Values.deployment.security.runAsGroup }}
        fsGroup: {{ default 0 .Values.deployment.security.fsGroup }}
      serviceAccountName: {{ include "mgmt-agent.serviceAccount" . }}
      imagePullSecrets:
        - name: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent-container-registry-key
      restartPolicy: Always
      containers:
        - name: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent
          image: {{ .Values.mgmtagent.image.url }}
          env:
          - name: HELM_DEPLOYMENT
            value: "true"
          - name: INSTALL_NAMESPACE
            value: {{ include "mgmt-agent.namespace" . }}
          resources:
            requests:
              cpu: {{ .Values.deployment.resource.request.cpuCore }}
              memory: {{ .Values.deployment.resource.request.memory }}
            limits:
              cpu: {{ .Values.deployment.resource.limit.cpuCore }}
              memory: {{ .Values.deployment.resource.limit.memory }}
          volumeMounts:
            - name: mgmtagent-secret
              mountPath: /opt/oracle/mgmtagent_secret
              readOnly: true
            - name: mgmtagent-pvc
              mountPath: /opt/oracle
            - name: mgmtagent-config
              mountPath: /opt/oracle/mgmtagent_config
            - mountPath: /tmp
              name: tmp
          securityContext:
           allowPrivilegeEscalation: false
           readOnlyRootFilesystem: true
      volumes:
        - name: mgmtagent-secret
          secret:
            secretName: {{ include "mgmt-agent.resourceNamePrefix" . }}-mgmt-agent-rsp
        - name: mgmtagent-config
          configMap:
            name: {{ include "mgmt-agent.resourceNamePrefix" . }}-metrics
        - emptyDir: {}
          name: tmp
  volumeClaimTemplates:
    - metadata:
        name: mgmtagent-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.deployment.storageClass }}
        storageClassName: {{ .Values.deployment.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.deployment.resource.request.storage }}
{{- end }}
